name: ci

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    strategy:
      matrix:
        os:
          - macos-26
          - ubuntu-24.04
          - windows-2025
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2

      - name: Install dependencies
        uses: ConorMacBride/install-package@v1.1.0
        with:
          brew: llvm
          apt: clang clang-format clang-tidy
          choco: llvm make

      - name: Add llvm to PATH on MacOS
        if: runner.os == 'macOS'
        run: echo "$(brew --prefix llvm)/bin" >> $GITHUB_PATH

      - name: Check formatting
        shell: bash
        run: |
          make format
          git diff --exit-code

      - name: Check for linting errors
        shell: bash
        run: make lint

      - name: Check for build errors
        shell: bash
        run: make
