name: ci

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    strategy:
      matrix:
        os:
          - macos-26
          - ubuntu-24.04
          - windows-2025
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2
      - name: Check formatting
        run: |
              make format
              git diff --exit-code
      - name: Check for linting errors
        run: make lint
      - name: Check for build errors
        run: make
